
// lib/main.dart

import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:workmanager/workmanager.dart';

import 'app/app.dart';
import 'core/services/workmanager_service.dart';
import 'firebase_options.dart';

/// Global instance of the local notifications plugin, initialized once
/// during app startup and reused across the app via dependency injection.
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

Future<void> main() async {
  // ---------------------------------------------------------------------
  // Flutter binding
  // ---------------------------------------------------------------------
  // Must be called before any plugin or platform channel usage.
  WidgetsFlutterBinding.ensureInitialized();

  // ---------------------------------------------------------------------
  // Global error handling
  // ---------------------------------------------------------------------
  // Routes all uncaught Flutter framework errors through a single handler
  // so they are logged consistently instead of crashing silently.
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.presentError(details);
    if (kDebugMode) {
      debugPrint('FlutterError: ${details.exceptionAsString()}');
    }
  };

  // Catches asynchronous errors that occur outside the Flutter framework's
  // own error zone (e.g. inside microtasks or platform channel callbacks).
  PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
    if (kDebugMode) {
      debugPrint('Uncaught platform error: $error');
    }
    return true;
  };

  // ---------------------------------------------------------------------
  // Device orientation
  // ---------------------------------------------------------------------
  // Lock the app to portrait-up only for a consistent layout experience.
  await SystemChrome.setPreferredOrientations(
    <DeviceOrientation>[DeviceOrientation.portraitUp],
  );

  // ---------------------------------------------------------------------
  // Firebase
  // ---------------------------------------------------------------------
  // Initializes Firebase Auth, Firestore, Messaging, and Storage using the
  // platform-specific configuration generated by the FlutterFire CLI.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ---------------------------------------------------------------------
  // Hive
  // ---------------------------------------------------------------------
  // Initializes Hive's storage location and prepares it for opening boxes
  // used for lightweight caching (preferences, orb state, sync metadata).
  await Hive.initFlutter();

  // ---------------------------------------------------------------------
  // Local notifications
  // ---------------------------------------------------------------------
  // Configures platform-specific initialization settings for scheduling
  // and displaying local notifications (class reminders, health nudges).
  const AndroidInitializationSettings androidInitSettings =
      AndroidInitializationSettings('@mipmap/ic_launcher');

  const DarwinInitializationSettings iosInitSettings =
      DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );

  const InitializationSettings notificationInitSettings =
      InitializationSettings(
    android: androidInitSettings,
    iOS: iosInitSettings,
  );

  await flutterLocalNotificationsPlugin.initialize(notificationInitSettings);

  // ---------------------------------------------------------------------
  // WorkManager
  // ---------------------------------------------------------------------
  // Initializes background task scheduling used for nightly attendance
  // checks, screen-time digests, and other periodic companion behaviors.
  await Workmanager().initialize(
    workManagerCallbackDispatcher,
    isInDebugMode: kDebugMode,
  );

  // ---------------------------------------------------------------------
  // App launch
  // ---------------------------------------------------------------------
  // Wraps the app in a ProviderScope so Riverpod providers are available
  // throughout the entire widget tree.
  runApp(
    const ProviderScope(
      child: StudentAiCompanionApp(),
    ),
  );
}
